### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [aritra-tech/Data-Structure-Algorithm#12]
The FORK link has incorrect repo name resulting into errors. Please get that corrected or assign it to me.

**Comment by aritra-tech** [comment]
It's working fine, could you please specify.

**Comment by Soumya-Kushwaha** [comment]
The links have the repo name as DATA-STRUCTURES-AND-ALGORITHMS while in actual, it is DATA-STRUCTURE-ALGORITHM

It's a little mistake, but made errors while i tried to fork & clone the repo yesterday

**Comment by aritra-tech** [comment]
Yah yah, I just relaized.
Got for it
