### ISSUE TITLE
Add problems on Linked Lists C++

### ISSUE THREAD

**Issue by ashmeet-chhabra** [aritra-tech/Data-Structure-Algorithm#134]
1. [Middle of the Linked List](https://leetcode.com/problems/middle-of-the-linked-list/)
1. [Remove Nth Node From End of List](https://leetcode.com/problems/remove-nth-node-from-end-of-list/)
1. [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/)
1. [Reverse Nodes in k-Group](https://leetcode.com/problems/reverse-nodes-in-k-group/)

**Comment by aritra-tech** [comment]
Sure
