### ISSUE TITLE
Add Array Question 

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#137]
1. [3Sum](https://leetcode.com/problems/3sum/)
2. [4Sum](https://leetcode.com/problems/4sum/)
3. [Set Matrix Zero](https://leetcode.com/problems/set-matrix-zeroes/)
4. [Rotate Image](https://leetcode.com/problems/rotate-image/)
5. [Product of Array Except Self](https://leetcode.com/problems/product-of-array-except-self/)

**Comment by GeekLord04** [comment]
Can I contribute to this issue?

**Comment by aritra-tech** [comment]
Yah, sure

**Comment by aritra-tech** [comment]
> Can't we add more problems??

For this issue these problems are ok.

**Comment by aritra-tech** [comment]
@CS50X-RGB if you want to contribute you can open your own issues.

**Comment by binayshaw7777** [comment]
I want to contribute @aritra-tech if you don't have any issue with that @GeekLord04 .

**Comment by aritra-tech** [comment]
Yeah sure @binayshaw7777

**Comment by JOYPAUL2001** [comment]
I want to work on this issue @aritra-tech

**Comment by aritra-tech** [comment]
Yeah, sure

**Comment by Rakesh9100** [comment]
Can I be assigned since 3 days over for previous assignee ?

**Comment by aritra-tech** [comment]
> Can I be assigned since 3 days over for previous assignee ? @aritra-tech

His health is not good, so he told me that he will complete his work within 1 or 2 days.

**Comment by Rakesh9100** [comment]
> > Can I be assigned since 3 days over for previous assignee ? @aritra-tech
> 
> His health is not good, so he told me that he will complete his work within 1 or 2 days.

Oh okay no issues.
