### ISSUE TITLE
More Problems on Array 

### ISSUE THREAD

**Issue by CS50X-RGB** [aritra-tech/Data-Structure-Algorithm#147]
1)[Median of 2 sorted Array](https://leetcode.com/problems/median-of-two-sorted-arrays/)
2)[Flipping of Image](https://leetcode.com/problems/flipping-an-image/)

**Comment by aritra-tech** [comment]
Both the links are opening the same problem.
Please check once @CS50X-RGB

**Comment by aritra-tech** [comment]
[Flipping of Image](https://leetcode.com/problems/flipping-an-image/)

**Comment by aritra-tech** [comment]
> now??

What now?

**Comment by aritra-tech** [comment]
> [Flipping of Image](https://leetcode.com/problems/flipping-an-image/)

This is the question link

**Comment by aritra-tech** [comment]
> > > now??
> > 
> > 
> > What now?
> 
> i changed the link sorry for the mistake

It's ok
