### ISSUE TITLE
Add more Array Questions

### ISSUE THREAD

**Issue by PriyanshuGarg26** [aritra-tech/Data-Structure-Algorithm#148]
1. [Group Anagrams](https://leetcode.com/problems/group-anagrams/)
2. [Longest Consecutive Sequence](https://leetcode.com/problems/longest-consecutive-sequence/)
3. [Pow(x, n)](https://leetcode.com/problems/powx-n/)
4. [Merge Intervals](https://leetcode.com/problems/merge-intervals/)
5. [Best Time to Buy & Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)

**Comment by PriyanshuGarg26** [comment]
Please Assign this issue to me

**Comment by aritra-tech** [comment]
Yah sure
