### ISSUE TITLE
Want to add 5 ArrayList Questions

### ISSUE THREAD

**Issue by Avik-creator** [aritra-tech/Data-Structure-Algorithm#155]
I will be adding 5 array list questions using Java.

**Comment by Avik-creator** [comment]
@aritra-tech please assign me these

**Comment by aritra-tech** [comment]
Send me the question links?

**Comment by Avik-creator** [comment]
https://www.geeksforgeeks.org/tag/java-arraylist/ @aritra-tech

**Comment by aritra-tech** [comment]
How mane questions you will do?

**Comment by Avik-creator** [comment]
5 questions which are most specific

**Comment by Avik-creator** [comment]
@aritra-tech Do I need to give all of the questions in a single file.

**Comment by Avik-creator** [comment]
@aritra-tech ??

**Comment by aritra-tech** [comment]
Under the ArrayList, package make a package name "Problems" and there make a separate package for each of the problems.

**Comment by Avik-creator** [comment]
ArrayList Shuffle, Java Program to Perform Binary Search on ArrayList, How to Prevent the Addition of Duplicate Elements to the Java ArrayList?,Join two ArrayLists in Java,Convert ArrayList to LinkedHashMap in Java. @aritra-tech Are these good enough?

**Comment by aritra-tech** [comment]
> ArrayList Shuffle, Java Program to Perform Binary Search on ArrayList, How to Prevent the Addition of Duplicate Elements to the Java ArrayList?,Join two ArrayLists in Java,Convert ArrayList to LinkedHashMap in Java. @aritra-tech Are these good enough?

Yeah yeah, great
