### ISSUE TITLE
Add Binary Search implementation in C++ and C

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#156]
add your code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Algorithm/Searching/BinarySearch)

**Comment by binayshaw7777** [comment]
I would contribute to it

**Comment by JOYPAUL2001** [comment]
I want to contribute

**Comment by aritra-tech** [comment]
Yeah, sure

**Comment by JOYPAUL2001** [comment]
Thanks @aritra-tech

**Comment by AnkitaKataria22** [comment]
I want to contribute

**Comment by aritra-tech** [comment]
> I want to contribute

Whoever first comments on the issue will be assigned first, if he, unfortunately, cannot complete his work within 4 days this issue will be assigned to you @AnkitaKataria22.
Hope you understand the rules.
