### ISSUE TITLE
Add Leetcode Existing Solutions of Java in C++ and C++ in Java

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#159]
1. [Jump Game II in  C++](https://leetcode.com/problems/jump-game-ii/)
2. Add README File
3. [Find Kth Largest in Java](https://leetcode.com/problems/kth-largest-element-in-an-array/)
4. [Peak Index in a Mountain Array in Java](https://leetcode.com/problems/peak-index-in-a-mountain-array/)
5. [Trapping Rain Water in C++](https://leetcode.com/problems/trapping-rain-water/)

**Comment by aritra-tech** [comment]
Sure.
