### ISSUE TITLE
Add Stack problems

### ISSUE THREAD

**Issue by Soumya-Kushwaha** [aritra-tech/Data-Structure-Algorithm#168]
https://practice.geeksforgeeks.org/problems/next-larger-element-1587115620/1?page=1&category[]=Stack&sortBy=submissions

https://practice.geeksforgeeks.org/problems/get-minimum-element-from-stack/1?page=1&category[]=Stack&sortBy=submissions

https://practice.geeksforgeeks.org/problems/parenthesis-checker2744/1?page=1&category[]=Stack&sortBy=submissions

**Comment by aritra-tech** [comment]
Create a package name **Problems** under the **stack** and then add the solutions. @Soumya-Kushwaha

**Comment by Soumya-Kushwaha** [comment]
Alright
