### ISSUE TITLE
AVL Tree in Java

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#17]
In the **Tree** folder create another package named **AVLTree** and in that folder create a java file and add the code.

Make sure to create a folder as I said above.

Comment on the issue to get assigned.

**Comment by Avik-creator** [comment]
@aritra-tech

**Comment by aritra-tech** [comment]
> AVL tree what to do in it could you please say it? Meaning we have to add basic AVL tree code?

Yah basic code of AVL tree

**Comment by afreenabegum** [comment]
Please do assign it to me!

**Comment by aritra-tech** [comment]
> Please do assign it to me!

Ok go for it
