### ISSUE TITLE
Add linked list questions

### ISSUE THREAD

**Issue by Akanksha-Sen** [aritra-tech/Data-Structure-Algorithm#170]

**Comment by aritra-tech** [comment]
Can you provide the question links?

**Comment by Akanksha-Sen** [comment]
1. https://practice.geeksforgeeks.org/problems/insert-in-a-sorted-list/1
2. https://leetcode.com/problems/linked-list-cycle-ii/submissions/
3. https://practice.geeksforgeeks.org/problems/identical-linked-lists/1
