### ISSUE TITLE
Bit Problems

### ISSUE THREAD

**Issue by SumitKanth** [aritra-tech/Data-Structure-Algorithm#188]
# I have 2 questions from leet code under Bit 
1.  Number of 1 bits
2. Complement of Base 10 Integer

# language -> c++

# I will contribute under HSOC22

**Comment by aritra-tech** [comment]
Sure

**Comment by SumitKanth** [comment]
What I want to do can you plz tell me

**Comment by aritra-tech** [comment]
> What I want to do can you plz tell me

Create a package under the Data Structure called Bit Manipulation and under the package keep your C++ files.
Hope you understand @SumitKanth

**Comment by SumitKanth** [comment]
Yes, thanks
