### ISSUE TITLE
1D DP Problems (Java)

### ISSUE THREAD

**Issue by binayshaw7777** [aritra-tech/Data-Structure-Algorithm#194]
1. House Robbers
2. Maximum Product Subarray
3. Unique Paths
4. Edit Distance

**Comment by aritra-tech** [comment]
Sure

**Comment by aritra-tech** [comment]
Sorry, @binayshaw7777 the time is over.

**Comment by GeekLord04** [comment]
Can I contribute to this issue?

**Comment by aritra-tech** [comment]
> Can I contribute to this issue?

Yeah, sure
