### ISSUE TITLE
Add problems on Greedy Algorithm | C++

### ISSUE THREAD

**Issue by ashmeet-chhabra** [aritra-tech/Data-Structure-Algorithm#197]
1. [Maximum Units on a Truck](https://leetcode.com/problems/maximum-units-on-a-truck/) (modification of Fractional Knapsack)
1. [Maximum Profit in Job Scheduling](https://leetcode.com/problems/maximum-profit-in-job-scheduling/)
1. [Maximum Number of Events That Can Be Attended](https://leetcode.com/problems/maximum-number-of-events-that-can-be-attended/)

**Comment by aritra-tech** [comment]
Sure

**Comment by Rishikavishnoi** [comment]
@aritra-tech can  I contribute to this issue?

**Comment by aritra-tech** [comment]
Sure @Rishikavishnoi

**Comment by Rishikavishnoi** [comment]
ok

**Comment by Rishikavishnoi** [comment]
@aritra-tech In which folder I have to add solution of these ques.

**Comment by aritra-tech** [comment]
Put it into the Arrays folder @Rishikavishnoi
