### ISSUE TITLE
Implement C++ code for Queue using Array

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#20]
Add the code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Data_Structure/Queue/Basic_operation/Queue_using_Array)

comment to get assigned.

**Comment by akashrchandran** [comment]
I would like to work on this issue.

**Comment by aritra-tech** [comment]
Go for it @akashrchandran
