### ISSUE TITLE
 Peak Index in a Mountain Array in java

### ISSUE THREAD

**Issue by AnkitaKataria22** [aritra-tech/Data-Structure-Algorithm#210]
https://leetcode.com/problems/peak-index-in-a-mountain-array/
An array arr a mountain if the following properties hold:

arr.length >= 3
There exists some i with 0 < i < arr.length - 1 such that:
arr[0] < arr[1] < ... < arr[i - 1] < arr[i]
arr[i] > arr[i + 1] > ... > arr[arr.length - 1]
Given a mountain array arr, return the index i such that arr[0] < arr[1] < ... < arr[i - 1] < arr[i] > arr[i + 1] > ... > arr[arr.length - 1].

You must solve it in O(log(arr.length)) time complexity.

**Comment by aritra-tech** [comment]
It's already done @AnkitaKataria22
