### ISSUE TITLE
Add Array Questions[use of binary Search]

### ISSUE THREAD

**Issue by AnkitaKataria22** [aritra-tech/Data-Structure-Algorithm#211]
1.[Find First and Last Position of Element in Sorted Array](https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/)
2.[Find Peak Element]https://leetcode.com/problems/find-peak-element/
3. [Find Smallest Letter Greater Than Target]https://leetcode.com/problems/find-peak-element/

**Comment by aritra-tech** [comment]
Sure
