### ISSUE TITLE
Add Stack Question

### ISSUE THREAD

**Issue by Rishikavishnoi** [aritra-tech/Data-Structure-Algorithm#213]
[The Celebrity Problem](https://practice.geeksforgeeks.org/problems/the-celebrity-problem/1)
[Parenthesis Checker](https://practice.geeksforgeeks.org/problems/parenthesis-checker2744/1)

**Comment by aritra-tech** [comment]
Sure

**Comment by Rishikavishnoi** [comment]
ok
