### ISSUE TITLE
Add Linkedlist problem in C++

### ISSUE THREAD

**Issue by tanya-gupta25** [aritra-tech/Data-Structure-Algorithm#216]
[Delete N nodes after M nodes of a linked list](https://practice.geeksforgeeks.org/problems/delete-n-nodes-after-m-nodes-of-a-linked-list/1)
[Delete the Middle Node of a Linked List](https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/)
[Remove loop in Linked List](https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1)

**Comment by tanya-gupta25** [comment]
I want to work on this issue under HSOC

**Comment by aritra-tech** [comment]
Go for it
