### ISSUE TITLE
Add more Stack Problems

### ISSUE THREAD

**Issue by Rishikavishnoi** [aritra-tech/Data-Structure-Algorithm#217]

**Comment by aritra-tech** [comment]
Do you mean Implementation?

**Comment by aritra-tech** [comment]
@Rishikavishnoi

**Comment by ZAPatil** [comment]
Can you please assign this issue to me.

**Comment by Rishikavishnoi** [comment]
[Evaluation of Postfix Expression](https://practice.geeksforgeeks.org/problems/evaluation-of-postfix-expression1735/1)
[Reverse a string using Stack](https://practice.geeksforgeeks.org/problems/reverse-a-string-using-stack/1)
