### ISSUE TITLE
Add 5 Hashmap Questions 

### ISSUE THREAD

**Issue by Avik-creator** [aritra-tech/Data-Structure-Algorithm#225]
Want to add 5 Hashmap Questions.

**Comment by Avik-creator** [comment]
@aritra-tech please assign me this

**Comment by aritra-tech** [comment]
Can you please give the link of the questions @Avik-creator

**Comment by Avik-creator** [comment]
https://www.geeksforgeeks.org/tag/java-hashmap/
@aritra-tech Please check.

**Comment by Avik-creator** [comment]
I will comment you again on which questions I have selected.

**Comment by aritra-tech** [comment]
> I will comment you again on which questions I have selected.

Ok, but after seeing the questions I will give the label to this issue.

**Comment by Avik-creator** [comment]
Check if a number is a Pangram or not, Converting Binary To Octal number using HashMap in Java, Convert HashMap to LinkedList in Java, Convert ArrayList to HashMap in Java, Check if Particular Key Exists in Java HashMap. @aritra-tech These are the questions I have selected could you please see them.

**Comment by aritra-tech** [comment]
Nice questions selected @Avik-creator 
Go for it
