### ISSUE TITLE
Add leetcode solutions of Searching problems

### ISSUE THREAD

**Issue by tanya-gupta25** [aritra-tech/Data-Structure-Algorithm#23]
Will add solutions of binary search problems from leetcode

**Comment by tanya-gupta25** [comment]
I want to work on this issue under HSSOC

**Comment by Robinrai2612** [comment]
@aritra-tech I want to work on this issue .Please assigned it.

Type: Documentation 
Language : Python

**Comment by aritra-tech** [comment]
> @aritra-tech I want to work on this issue .Please assigned it.
> 
> Type: Documentation Language : Python

Sorry @Robinrai2612 the issue was created by her so she will get the issue. You can make your own issue as I said to you.
Thank you
