### ISSUE TITLE
How Many Numbers Are Smaller Than the Current Number[Leetcode]

### ISSUE THREAD

**Issue by AnkitaKataria22** [aritra-tech/Data-Structure-Algorithm#231]
https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number/
Given the array nums, for each nums[i] find out how many numbers in the array are smaller than it. That is, for each nums[i] you have to count the number of valid j's such that j != i and nums[j] < nums[i].

Return the answer in an array.

**Comment by aritra-tech** [comment]
Put it into the Leetcode problems package under the array
