### ISSUE TITLE
Add a sorting technique - Dutch National Flag Algorithm (C++)

### ISSUE THREAD

**Issue by ashmeet-chhabra** [aritra-tech/Data-Structure-Algorithm#24]
I will add the Dutch National Flag Algorithm, also called the 3-way Quick Sort, and will be using C++ to implement it.

**Comment by ashmeet-chhabra** [comment]
I want to work on this issue under HSSOC

**Comment by aritra-tech** [comment]
Yeah sure, but please make a folder named "Dutch National Flag Algo" then under that folder create your file.

**Comment by ashmeet-chhabra** [comment]
Thanks. The folder should be inside the Sorting folder or in Algorithms?

**Comment by aritra-tech** [comment]
> Thanks. The folder should be inside the Sorting folder or in Algorithms?

[Here only make a folder name and add the file](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Algorithm/Sorting)
