### ISSUE TITLE
Adding LinkedList Question

### ISSUE THREAD

**Issue by Rishikavishnoi** [aritra-tech/Data-Structure-Algorithm#242]
[ReverseLinkedList](https://leetcode.com/problems/reverse-linked-list/)
[Middle of the Linked List](https://leetcode.com/problems/reverse-linked-list/)

**Comment by aritra-tech** [comment]
In which language you will do @Rishikavishnoi ?
Because it is already done in C++.

**Comment by Rishikavishnoi** [comment]
Java

**Comment by Rishikavishnoi** [comment]
@aritra-tech

**Comment by aritra-tech** [comment]
Ok ok go for it
