### ISSUE TITLE
Add Array Question 

### ISSUE THREAD

**Issue by Rishikavishnoi** [aritra-tech/Data-Structure-Algorithm#254]
[Merge Overlapping Subintervals](https://takeuforward.org/data-structure/merge-overlapping-sub-intervals/)
[Merge two sorted Arrays without extra space](https://takeuforward.org/data-structure/merge-two-sorted-arrays-without-extra-space/)
[Find the duplicate in an array of N+1 integers](https://takeuforward.org/data-structure/find-the-duplicate-in-an-array-of-n1-integers/).

**Comment by aritra-tech** [comment]
@Rishikavishnoi second question is already done in the repo so if you want you can do another question of Array.

**Comment by Rishikavishnoi** [comment]
@aritra-tech ok so I will add ques 1 and 3 only

**Comment by aritra-tech** [comment]
> @aritra-tech ok so I will add ques 1 and 3 only

Ok
