### ISSUE TITLE
Add Binary Tree Problems

### ISSUE THREAD

**Issue by coderSuren** [aritra-tech/Data-Structure-Algorithm#256]
I would like to add following traversal problems to [Data_Structure](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Data_Structure)/[Tree](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Data_Structure/Tree)/[Traversals](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Data_Structure/Tree/Traversals)/ Folder:

- [Vertical Order Traversal of a Binary Tree](https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree)
-  [Construct Binary Tree from Preorder and Inorder Traversal](https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal)
- [Binary Tree Level Order Traversal](https://leetcode.com/problems/binary-tree-level-order-traversal)

Please assign me this issue

**Comment by aritra-tech** [comment]
Sure @coderSuren go for it
