### ISSUE TITLE
Some Leetcode String Problems

### ISSUE THREAD

**Issue by CS50X-RGB** [aritra-tech/Data-Structure-Algorithm#261]
<a href ="https://leetcode.com/problems/valid-palindrome/">1)Valid Palindrome</a>
<a href ="https://leetcode.com/problems/count-asterisks/">2)Count Asterisks</a>
<a href ="https://leetcode.com/problems/first-letter-to-appear-twice/">3)First Letter Appear Twice</a>

**Comment by CS50X-RGB** [comment]
@arita-tech actually there is some problem here
i made a pr yesterday which files for this issue to what should i do now

**Comment by CS50X-RGB** [comment]
<a href = "https://github.com/aritra-tech/Data-Structure-Algorithm/pull/281/commits/4f0a220f17f47b7aba575d4549a7480d6b2d5134">Here it is</a>

**Comment by aritra-tech** [comment]
Don't need to worry so, copy the codes that you have done and delete them and then create a pr for this issue.
Hope you understand @CS50X-RGB

**Comment by CS50X-RGB** [comment]
Ohh ok ☺
