### ISSUE TITLE
Add Some Array Solutions

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#266]
1. [Container With Most Water](https://leetcode.com/problems/container-with-most-water/)
2. [Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number/)
3. [4Sum](https://leetcode.com/problems/4sum/)
4. [How Many Numbers Are Smaller Than the Current Number](https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number/)

**Comment by aritra-tech** [comment]
In which language @Rakesh9100 ?

**Comment by Rakesh9100** [comment]
> In which language @Rakesh9100 ?

C++

**Comment by aritra-tech** [comment]
Ok sure go for it.
