### ISSUE TITLE
Queue Questions in C++

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#279]
1. Design Circular Deque
2. Product of the Last K Numbers
3. Design Circular Queue
4. Maximum Sum Circular Subarray

**Comment by Rakesh9100** [comment]
Hey bro, 3 ques should have level 3 but if not then adding one more ques and total 4 ques should change the level to 3 I believe @aritra-tech

**Comment by aritra-tech** [comment]
Sorry @Rakesh9100 yes it should be level 3
