### ISSUE TITLE
Want to Add LeetCode Sorting Questions

### ISSUE THREAD

**Issue by Avik-creator** [aritra-tech/Data-Structure-Algorithm#282]
It Will have the following Questions:

* [2344. Minimum Deletions to Make Array Divisible](https://leetcode.com/problems/minimum-deletions-to-make-array-divisible)
* [2273. Find Resultant Array After Removing Ana](https://leetcode.com/problems/find-resultant-array-after-removing-anagrams)
* [2332. The Latest Time to Catch a Bus](https://leetcode.com/problems/the-latest-time-to-catch-a-bus)
* [2333. Minimum Sum of Squared Difference](https://leetcode.com/problems/minimum-sum-of-squared-difference)

**Comment by Avik-creator** [comment]
@aritra-tech Please assign me this.

**Comment by aritra-tech** [comment]
Sure @Avik-creator
