### ISSUE TITLE
Introduction to Array

### ISSUE THREAD

**Issue by MohammadKaif1** [aritra-tech/Data-Structure-Algorithm#285]
Hey @aritra-tech Can I add introduction on array from scratch.
Because this repo is on DSA and I am wondering that one who follows this repo for learning DSA will definitely have to start from basic and there is no basics of Array.
 So, that's why I want to work on this issue.

**Comment by aritra-tech** [comment]
Yeah, sure.
You have also one issue left @MohammadKaif1 issue no #240

**Comment by MohammadKaif1** [comment]
Questions that I wanted to add in issue no. #240  are same as I wants to add.

**Comment by aritra-tech** [comment]
Ok, so I am closing that issue @MohammadKaif1
