### ISSUE TITLE
Add Recursion Leetcode Ques in C++

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#301]
1. Fibonacci Number
2. Reverse String
3. Power of Three
4. Power of Four

**Comment by aritra-tech** [comment]
@Rakesh9100 question no 3 is already done.
Choose any other question and send the link.

**Comment by Rakesh9100** [comment]
> @Rakesh9100 question no 3 is already done. Choose any other question and send the link.

Done

**Comment by aritra-tech** [comment]
Nice
