### ISSUE TITLE
Add BitManipulation Ques in CPP

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#311]
1. [Divide Two Integers](https://leetcode.com/problems/divide-two-integers/)
2. [Subsets](https://leetcode.com/problems/subsets/)
3. [Maximum Product of Word Lengths](https://leetcode.com/problems/maximum-product-of-word-lengths/)

**Comment by aritra-tech** [comment]
Sure
