### ISSUE TITLE
Tree Ques in CPP

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#313]
1. [Binary Tree Level Order Traversal](https://leetcode.com/problems/binary-tree-level-order-traversal/)
2. [Unique Binary Search Trees](https://leetcode.com/problems/unique-binary-search-trees/)
3. [Unique Binary Search Trees II](https://leetcode.com/problems/unique-binary-search-trees-ii/)

**Comment by aritra-tech** [comment]
Sure
