### ISSUE TITLE
Adding Recursion Ques.

### ISSUE THREAD

**Issue by Rishikavishnoi** [aritra-tech/Data-Structure-Algorithm#314]
[Print all permutations of a string/array](https://takeuforward.org/data-structure/print-all-permutations-of-a-string-array/)
[M coloring Problem](https://takeuforward.org/data-structure/m-coloring-problem/)

**Comment by aritra-tech** [comment]
@Rishikavishnoi you are doing the problems it's good but the links which you have given, there already exists the code in C++ and Java. You solve but don't just copy the code try to understand and if you face any problem tell me I will help you out.

**Comment by Rishikavishnoi** [comment]
hey! @aritra-tech I always solve the question and then upload it in these repositories to contribute, not just copy or best ...so now as these question already exists, you can close the issue . I'll create some new issues.

**Comment by aritra-tech** [comment]
> hey! @aritra-tech I always solve the question and then upload it in these repositories to contribute, not just copy or best ...so now as these question already exists, you can close the issue . I'll create some new issues.

Ok
