### ISSUE TITLE
Array Questions in Java

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#328]
1. [Pascal's Triangle](https://leetcode.com/problems/pascals-triangle/)
2. [Next Permutation](https://leetcode.com/problems/next-permutation/)
3. [Maximum Subarray](https://leetcode.com/problems/maximum-subarray/)

Add your code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet) under the **Arrays** section.

**Important:**
- Create a package for each question
- And create a README file for each question, which will consist of the problem link, and time complexity and you have to write the approach towards the solution **(both brute force and optimal one)**

**Comment by Rakesh9100** [comment]
Kindly assign this @aritra-tech

**Comment by aritra-tech** [comment]
Sure
