### ISSUE TITLE
Add Array Questions in Java

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#329]
1. [Sort Colors](https://leetcode.com/problems/sort-colors/)
2. [Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/)

Add your code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet) under the Arrays section.

**Important:**

- Create a package for each question
- And create a README file for each question, which will consist of the problem link, and time complexity and you have to write the approach towards the solution **(both brute force and optimal one)**

**Comment by Rakesh9100** [comment]
Pls assign this to me @aritra-tech

**Comment by aritra-tech** [comment]
Sure
