### ISSUE TITLE
Add Linked List question of Striver SDE Sheet in Java

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#330]
1. [Middle of the Linked List](https://leetcode.com/problems/middle-of-the-linked-list/)
2. [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/)
3. [Delete Node in a Linked List](https://leetcode.com/problems/delete-node-in-a-linked-list/)

Add your [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet) under the **Linked List** package

**Important:**

- Create a package for each question
- And create a README file for each question, which will consist of the problem link, and time complexity and you have to write the approach towards the solution **(both brute force and optimal one)**

**Comment by Rishikavishnoi** [comment]
I want to do these plz assign me

**Comment by Rakesh9100** [comment]
Pls assign this to me @aritra-tech

**Comment by aritra-tech** [comment]
Sure
