### ISSUE TITLE
Linked List Questions of Striver SDE Sheet

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#331]
1. [Remove Nth Node From End of List](https://leetcode.com/problems/remove-nth-node-from-end-of-list/)
2. [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/)

Add your [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet) under the Linked List package

**Important:**

- Create a package for each question
- And create a README file for each question, which will consist of the problem link, and time complexity and you have to write the approach towards the solution **(both brute force and optimal one)**

**Comment by JOYPAUL2001** [comment]
I want to work on this issue @aritra-tech

**Comment by aritra-tech** [comment]
Sure

**Comment by Rakesh9100** [comment]
Can I work on this ? @aritra-tech
