### ISSUE TITLE
String Questions of Striver's SDE Sheet in C++

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#332]
1. [Reverse Words in a String](https://leetcode.com/problems/reverse-words-in-a-string/)
2. [Roman to Integer](https://leetcode.com/problems/roman-to-integer/)
3. [Longest Common Prefix](https://leetcode.com/problems/longest-common-prefix/)

Add your [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet) under the **Strings** package

**Important:**

- Create a package for each question
- And create a README file for each question, which will consist of the problem link, and time complexity and you have to write the approach towards the solution **(both brute force and optimal one)**

**Comment by tanya-gupta25** [comment]
I would like to work on this issue!

**Comment by aritra-tech** [comment]
Yeah, sure @tanya-gupta25

**Comment by Rakesh9100** [comment]
Can I be assigned @aritra-tech

**Comment by tanya-gupta25** [comment]
> Can I be assigned @aritra-tech

Hey @Rakesh9100 I'm working on this issue

**Comment by Rakesh9100** [comment]
> > Can I be assigned @aritra-tech
> 
> Hey @Rakesh9100 I'm working on this issue

Okay 👍
