### ISSUE TITLE
Add String Questions in Java

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#333]
1. [String to Integer](https://leetcode.com/problems/string-to-integer-atoi/)
2. [Repeated String Match](https://leetcode.com/problems/repeated-string-match/)

Add your [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet) under the **String** package

**Important**:

Create a package for each question
And create a README file for each question, which will consist of the problem link, and time complexity and you have to write the approach towards the solution **(both brute force and optimal one)**

**Comment by Avik-creator** [comment]
@aritra-tech i want to work on this

**Comment by aritra-tech** [comment]
You are already assigned with 2 issues @Avik-creator.
Let others also participate.
Hope you get it @Avik-creator , if there is no comments within  days I will assign you.

**Comment by Avik-creator** [comment]
@aritra-tech no worries

**Comment by Rishikavishnoi** [comment]
@aritra-tech I want to work in these issue as now I have no other issue to work . so pls assign me

**Comment by aritra-tech** [comment]
> @aritra-tech I want to work in these issue as now I have no other issue to work . so pls assign me

Sure @Rishikavishnoi
