### ISSUE TITLE
Bellman-Ford Algorithm in CPP

### ISSUE THREAD

**Issue by vickyrules** [aritra-tech/Data-Structure-Algorithm#34]
Single source shortest path with negative weight edges

**Comment by vickyrules** [comment]
@aritra-tech 
this one too please.

**Comment by afreenabegum** [comment]
@aritra-tech 
I would like to work on this, please do assign it to me.

**Comment by aritra-tech** [comment]
> @aritra-tech I would like to work on this, please do assign it to me.

Sorry, but the issue is created by him so he will only be assigned.

**Comment by afreenabegum** [comment]
@aritra-tech  okay, that's fine.

**Comment by aritra-tech** [comment]
@vickyrules you can work on this issue now
All the best.
