### ISSUE TITLE
Adding leetcode problems on searching

### ISSUE THREAD

**Issue by deepshikha2708** [aritra-tech/Data-Structure-Algorithm#341]

**Comment by deepshikha2708** [comment]
@aritra-tech will you assign me this issue?

**Comment by aritra-tech** [comment]
Which questions?

**Comment by deepshikha2708** [comment]
![image](https://user-images.githubusercontent.com/80972038/184961475-f8ad758b-a95c-46d5-8c49-0dad6373daa7.png)
 this question?

**Comment by aritra-tech** [comment]
Yeah sure
