### ISSUE TITLE
Add Linkedlist Problems in C++

### ISSUE THREAD

**Issue by tanya-gupta25** [aritra-tech/Data-Structure-Algorithm#343]
[Convert Binary Number in a Linked List to Integer](https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/)
[Remove Linked List Elements](https://leetcode.com/problems/remove-linked-list-elements/)
[Multiply two numbers represented by Linked Lists](https://practice.geeksforgeeks.org/problems/multiply-two-linked-lists/1)
[Delete without head pointer](https://practice.geeksforgeeks.org/problems/delete-without-head-pointer/1)

**Comment by aritra-tech** [comment]
Sure

**Comment by tanya-gupta25** [comment]
Hey @aritra-tech adding 1 more problem will make it level-3?

**Comment by aritra-tech** [comment]
> Hey @aritra-tech adding 1 more problem will make it level-3?

No no these are all easy and simple questions so level 2 is fine
