### ISSUE TITLE
Add more Array Questions in java

### ISSUE THREAD

**Issue by Rishikavishnoi** [aritra-tech/Data-Structure-Algorithm#353]
[Majority Element (>N/2 times)](https://leetcode.com/problems/majority-element/) 
[Majority Element (>N/3 times)](https://leetcode.com/problems/majority-element-ii/) 
[Grid Unique Path](https://leetcode.com/problems/unique-paths/)

**Comment by Rishikavishnoi** [comment]
@aritra-tech assign me

**Comment by aritra-tech** [comment]
Add your [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet) under the Arrays package @Rishikavishnoi 

**Important:**

- Create a package for each question
- And create a README file for each question, which will consist of the problem link, and time complexity and you have to write the approach towards the solution (both brute force and optimal one)
