### ISSUE TITLE
Add Searching Algorithms in C++

### ISSUE THREAD

**Issue by Maruti54** [aritra-tech/Data-Structure-Algorithm#358]
1. Sublist Search (Search a linked list in another list)
2. Fibonacci Search
3. The Ubiquitous Binary Search
4. Recursive program to linearly search an element in a given array

**Comment by Maruti54** [comment]
@aritra-tech please assign me this issue

**Comment by aritra-tech** [comment]
Sure, but @Maruti54 please make a package for every question or algorithm you do, so that other users can find them easily and it looks organized.
Hope you understand @Maruti54 .

**Comment by Maruti54** [comment]
Yeah I will

**Comment by Maruti54** [comment]
Please make it Level 3
