### ISSUE TITLE
Linked List Questions of Striver SDE Sheet in C++

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#361]
1. [Reverse Nodes in k-Group](https://leetcode.com/problems/reverse-nodes-in-k-group/)
2. [Intersection of Two Linked Lists](https://leetcode.com/problems/intersection-of-two-linked-lists/)
3. [Linked List Cycle II](https://leetcode.com/problems/linked-list-cycle-ii/)

**Comment by Rakesh9100** [comment]
> 

Okay will open a new issue after doing in C++. Not to worry. @aritra-tech

**Comment by Rakesh9100** [comment]
> Okay will open a new issue after doing in C++. Not to worry. @aritra-tech

Okay will open a new issue after doing in C++. Not to worry. @aritra-tech

**Comment by Rakesh9100** [comment]
> Can you also do it in Java @Rakesh9100? I am not forcing you I am just asking if you can do it or not.

Okay will open a new issue after doing in C++. Not to worry. @aritra-tech

**Comment by aritra-tech** [comment]
> > Can you also do it in Java @Rakesh9100? I am not forcing you I am just asking if you can do it or not.
> 
> Okay will open a new issue after doing in C++. Not to worry. @aritra-tech

Leave it I will do the Java programs. No need to worry
