### ISSUE TITLE
Add String Questions of Striver's SDE Sheet in C++

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#362]
1. [Compare Version Numbers](https://leetcode.com/problems/compare-version-numbers/)
2. [Count and Say](https://leetcode.com/problems/count-and-say/)
3. [Valid Anagram](https://leetcode.com/problems/valid-anagram/)

**Comment by aritra-tech** [comment]
Can you also do it in Java @Rakesh9100?
I am not forcing you I am just asking if you can do it or not.

**Comment by Rakesh9100** [comment]
> Can you also do it in Java @Rakesh9100? I am not forcing you I am just asking if you can do it or not.

Can I ask why do you want in Java and not in C++ most time ? Just asking 😅 @aritra-tech

**Comment by aritra-tech** [comment]
> > Can you also do it in Java @Rakesh9100? I am not forcing you I am just asking if you can do it or not.
> 
> Can I ask why do you want in Java and not in C++ most time ? Just asking 😅 @aritra-tech

I just told to do it in both languages.
You continue with C++. @Rakesh9100
