### ISSUE TITLE
Add String Questions in C++

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#363]
- [String to Integer](https://leetcode.com/problems/string-to-integer-atoi/)  and add your code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet/Strings/StringToInteger)
- [Repeated String Match](https://leetcode.com/problems/repeated-string-match/)  and add your code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet/Strings/RepeatedStringMatch)

**Comment by Rakesh9100** [comment]
Kindly assign @aritra-tech
