### ISSUE TITLE
Add Linked List question of Striver SDE Sheet in C++

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#364]
- [Middle of the Linked List](https://leetcode.com/problems/middle-of-the-linked-list/) and add your code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet/Linked_List/MiddleOfLinkedList)
- [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/) and add your code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet/Linked_List/MergeTwoSortedArray)
- [Delete Node in a Linked List](https://leetcode.com/problems/delete-node-in-a-linked-list/) and add your code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet/Linked_List/DeleteNodeInLinkedList)

**Comment by Rakesh9100** [comment]
Assign this issue to me @aritra-tech
