### ISSUE TITLE
String Questions of Striver's SDE Sheet in Java

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#370]
1. [Compare Version Numbers](https://leetcode.com/problems/compare-version-numbers/)
2. [Count and Say](https://leetcode.com/problems/count-and-say/)
3. [Valid Anagram](https://leetcode.com/problems/valid-anagram/)

**Comment by Rakesh9100** [comment]
Kindly assign to add in Java @aritra-tech

**Comment by aritra-tech** [comment]
Yeah, sure but the next time try to solve the questions in both languages (Java as well as C++).
@Rakesh9100

**Comment by Rakesh9100** [comment]
> 

Okay will do for sure, but level should be changed to 3 pls . @aritra-tech

**Comment by aritra-tech** [comment]
> > 
> 
> Okay will do for sure, but level should be changed to 3 I believe pls . @aritra-tech

Level 2 is fine because you have already done it in Java so you know the intuition behind the problem so level 2 is fine.

**Comment by Rakesh9100** [comment]
> > > 
> > 
> > 
> > Okay will do for sure, but level should be changed to 3 I believe pls . @aritra-tech
> 
> Level 2 is fine because you have already done it in Java so you know the intuition behind the problem so level 2 is fine.

Okay 👍
