### ISSUE TITLE
Add Queue Question in Java

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#375]
1. [Design Circular Deque](https://leetcode.com/problems/design-circular-deque/)
2. [Maximum Sum Circular Subarray](https://leetcode.com/problems/maximum-sum-circular-subarray/)
3. [Find the Winner of the Circular Game](https://leetcode.com/problems/find-the-winner-of-the-circular-game/)

**Comment by aritra-tech** [comment]
Sure
