### ISSUE TITLE
Add Dynamic Programming Questions

### ISSUE THREAD

**Issue by tanya-gupta25** [aritra-tech/Data-Structure-Algorithm#377]
[House Robber](https://leetcode.com/problems/house-robber/)
[House Robber II](https://leetcode.com/problems/house-robber-ii/)
[Frog Jump](https://www.codingninjas.com/codestudio/problems/frog-jump_3621012)

Will add solutions of all these ques in C++

- Approaches to be added - Recursion, Memoization, Tabulation, Space Optimization
- Will add time & space complexity for each approach

**Comment by aritra-tech** [comment]
Sure
