### ISSUE TITLE
Add Stack Questions in Java

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#379]
1. [Maximum Binary Tree](https://leetcode.com/problems/maximum-binary-tree/)
2. [Minimum Add to Make Parentheses Valid](https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/)
3. [Remove Duplicate Letters](https://leetcode.com/problems/remove-duplicate-letters/)

**Comment by Rakesh9100** [comment]
Kindly assign this @aritra-tech

**Comment by aritra-tech** [comment]
Sure
