### ISSUE TITLE
Add more Matrix Problems

### ISSUE THREAD

**Issue by CS50X-RGB** [aritra-tech/Data-Structure-Algorithm#383]
1) <a href = "https://leetcode.com/problems/the-k-weakest-rows-in-a-matrix/">The k-weakest rows in a matrix</a>
2) <a href = "https://leetcode.com/problems/search-a-2d-matrix/">Search in 2d matrix</a>
3) <a href = "https://leetcode.com/problems/word-search/description/">Word Search</a>

**Comment by CS50X-RGB** [comment]
@aritra-tech can i get assigned??

**Comment by aritra-tech** [comment]
Yeah, sure but @CS50X-RGB try to do questions from other topics also there are more important topics than Matrix.

**Comment by CS50X-RGB** [comment]
> Yeah, sure but @CS50X-RGB try to do questions from other topics also there are more important topics than Matrix.
> 

Actually I have learned till matrix and linked list so i am trying to practice question and put issue here will try for next topic for sure

**Comment by aritra-tech** [comment]
> > Yeah, sure but @CS50X-RGB try to do questions from other topics also there are more important topics than Matrix.
> 
> Actually I have learned till matrix and linked list so i am trying to practice question and put issue here will try for next topic for sure from different topic

Oo ok then,sorry I didn't knew that

**Comment by aritra-tech** [comment]
Keep practicing @CS50X-RGB

**Comment by CS50X-RGB** [comment]
> > > Yeah, sure but @CS50X-RGB try to do questions from other topics also there are more important topics than Matrix.
> > 
> > Actually I have learned till matrix and linked list so i am trying to practice question and put issue here will try for next topic for sure from different topic
> 
> Oo ok then,sorry I didn't knew that

No problem ☺
