### ISSUE TITLE
Add more Linked list ques. (SDE Sheet)

### ISSUE THREAD

**Issue by Rishikavishnoi** [aritra-tech/Data-Structure-Algorithm#384]
[Find the starting point of the Loop of LinkedList](https://leetcode.com/problems/linked-list-cycle-ii/)
[Flattening of a LinkedList](https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1)
[Find intersection point of Y LinkedList](https://leetcode.com/problems/intersection-of-two-linked-lists/)
[Check if a LinkedList is palindrome or not.](https://leetcode.com/problems/palindrome-linked-list/)

**Comment by Rishikavishnoi** [comment]
@aritra-tech assign it to me

**Comment by aritra-tech** [comment]
Sure @Rishikavishnoi
