### ISSUE TITLE
Graph Algorithms in C++

### ISSUE THREAD

**Issue by Maruti54** [aritra-tech/Data-Structure-Algorithm#387]
1. Topological Sort
2. Johnson's algorithm
3. Hierholzer’s Algorithm
4. Bridges in a graph

**Comment by Maruti54** [comment]
@aritra-tech  please assign me this issue.

**Comment by aritra-tech** [comment]
Yeah, sure but also explain the intuition behind the code for the begginers. 
Hope you understand @Maruti54

**Comment by Maruti54** [comment]
Yeah, I will try to explain.
