### ISSUE TITLE
Add Array Questions in Java

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#388]
1. [Maximum Profit in Job Scheduling](https://leetcode.com/problems/maximum-profit-in-job-scheduling/)
2. [Find All Duplicates in an Array](https://leetcode.com/problems/find-all-duplicates-in-an-array/)
3. [Flipping an Image](https://leetcode.com/problems/flipping-an-image/)

**Comment by aritra-tech** [comment]
Sure

**Comment by Rakesh9100** [comment]
Please change to Level 3 since hard question will be done @aritra-tech

**Comment by aritra-tech** [comment]
> Please change to Level 3 since hard question will be done @aritra-tech

[Find All Duplicates in an Array](https://leetcode.com/problems/find-all-duplicates-in-an-array/)
[Flipping an Image](https://leetcode.com/problems/flipping-an-image/)

These two questions are elementary that's why I gave it to level 2 and points don't matter keep practicing so that your problem-solving skills become good.

**Comment by Rakesh9100** [comment]
> > Please change to Level 3 since hard question will be done @aritra-tech
> 
> [Find All Duplicates in an Array](https://leetcode.com/problems/find-all-duplicates-in-an-array/) [Flipping an Image](https://leetcode.com/problems/flipping-an-image/)
> 
> These two questions are elementary that's why I gave it to level 2 and points don't matter keep practicing so that your problem-solving skills become good.

Yes practicing is in one's own hand, and it should be consistent, but we all know that open source event competition is going on, so points should also be focused till this program remains. Hope you understand @aritra-tech
