### ISSUE TITLE
Recursion Questions in CPP

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#389]
1. [Pow(x, n)](https://leetcode.com/problems/powx-n/)
2. [Elimination Game](https://leetcode.com/problems/elimination-game/)
3. [Power of Two](https://leetcode.com/problems/power-of-two/)
4. [Swap Nodes in Pairs](https://leetcode.com/problems/swap-nodes-in-pairs/)

**Comment by aritra-tech** [comment]
[Maximize Number of Nice Divisors](https://leetcode.com/problems/maximize-number-of-nice-divisors/) is already done in CPP

**Comment by Rakesh9100** [comment]
Changed and also added one more question @aritra-tech

**Comment by aritra-tech** [comment]
Ok , continue
