### ISSUE TITLE
Add Graph Problems

### ISSUE THREAD

**Issue by tanya-gupta25** [aritra-tech/Data-Structure-Algorithm#393]
[Max Area of Island](https://leetcode.com/problems/max-area-of-island/)
[ Is Graph Bipartite?](https://leetcode.com/problems/is-graph-bipartite/)
[Flood Fill](https://leetcode.com/problems/flood-fill/)

- will add all these graph problems using c++

**Comment by aritra-tech** [comment]
Sure

**Comment by tanya-gupta25** [comment]
Shall I add one more medium level ques to make it level-3?

**Comment by aritra-tech** [comment]
Don't run for points, you are practicing for your betterment in DSA. Points don't matter, solving questions matters the most.
And it will be a level 2 issue only I will not change it.

**Comment by tanya-gupta25** [comment]
> Don't run for points, you are practicing for your betterment in DSA. Points don't matter, solving questions matters the most. And it will be a level 2 issue only I will not change it.

Cool!
