### ISSUE TITLE
Linked List Questions of Striver's SDE Sheet in Java & C++

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#403]
- [Linked List Cycle](https://leetcode.com/problems/linked-list-cycle/)
- [Palindrome Linked List](https://leetcode.com/problems/palindrome-linked-list/)
- [Flattening a Linked List](https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1)

Add your [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet) under the Linked List package

**Important:**

- Create a package for each question
- And create a README file for each question, which will consist of the problem link, and time complexity and you have to write the approach towards the solution (both brute force and optimal one)

**Comment by Rakesh9100** [comment]
Assign me @aritra-tech

**Comment by aritra-tech** [comment]
Sure
