### ISSUE TITLE
String Questions of Striver SDE Sheet in Java & C++

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#404]
- [Z Algorithm](https://www.codingninjas.com/codestudio/problems/1112619?topList=striver-sde-sheet-problems&utm_source=striver&utm_medium=website)
- [Find Pattern in String - KMP Algorithm](https://www.codingninjas.com/codestudio/problems/1112621?topList=striver-sde-sheet-problems&utm_source=striver&utm_medium=website)
- [Minimum Characters For Palindrome](https://www.codingninjas.com/codestudio/problems/893000?topList=striver-sde-sheet-problems&utm_source=striver&utm_medium=website)

Add your code [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Striver_SDE_Sheet) under the Strings Section

**Important:**

- Create a package for each question
- And create a README file for each question, which will consist of the problem link, and time complexity and you have to write the approach towards the solution (both brute force and optimal one)

**Comment by Rishikavishnoi** [comment]
@aritra-tech assign it to me

**Comment by aritra-tech** [comment]
Sure
