### ISSUE TITLE
Add Linkedlist Problems

### ISSUE THREAD

**Issue by tanya-gupta25** [aritra-tech/Data-Structure-Algorithm#405]
[Flattening a Linked List](https://practice.geeksforgeeks.org/problems/flattening-a-linked-list/1)
[Merge Sort for Linked List](https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1)
[Palindrome Linked List](https://leetcode.com/problems/palindrome-linked-list/)
[Odd Even Linked List](https://leetcode.com/problems/odd-even-linked-list/)

- will add these questions in c++

**Comment by aritra-tech** [comment]
Yeah, sure

**Comment by Rakesh9100** [comment]
Can I be assigned and work on this ? @aritra-tech

**Comment by tanya-gupta25** [comment]
> Can I be assigned and work on this ? @aritra-tech

 @Rakesh9100  Hey sorry but I'm working on this PR

**Comment by Rakesh9100** [comment]
> > Can I be assigned and work on this ? @aritra-tech
> 
> @Rakesh9100 Hey sorry but I'm working on this PR

Okay no issues. It's been 9 days so I asked.
