### ISSUE TITLE
Binary String Duplication Problem

### ISSUE THREAD

**Issue by deepshikha2708** [aritra-tech/Data-Structure-Algorithm#413]
![image](https://user-images.githubusercontent.com/80972038/186636896-04a0e953-d82c-47d5-8a07-b9cc5031b5f0.png)

**Comment by deepshikha2708** [comment]
@aritra-tech can you assign me this issue?

**Comment by aritra-tech** [comment]
sure

**Comment by deepshikha2708** [comment]
in which folder should i put this question exactly?

**Comment by aritra-tech** [comment]
> in which folder should i put this question exactly?

Under the data structure folder, there is a folder named BitManipulation
