### ISSUE TITLE
Some Matrix & String Questions

### ISSUE THREAD

**Issue by CS50X-RGB** [aritra-tech/Data-Structure-Algorithm#418]
<A HREF = "https://leetcode.com/problems/implement-strstr/">1) Implement strStr()</a>
<A HREF = "https://leetcode.com/problems/convert-1d-array-into-2d-array/">2)  1D array to 2D array</a>
<a href = "https://leetcode.com/problems/determine-whether-matrix-can-be-obtained-by-rotation/"> 3) Determine matrix can be obtained by rotation or not</a>
<a href = "https://leetcode.com/problems/available-captures-for-rook/">4) Available captures for rook</a>

**Comment by CS50X-RGB** [comment]
@aritra-tech can i get this issue assigned plz

**Comment by aritra-tech** [comment]
Sure @CS50X-RGB
