### ISSUE TITLE
Disintegrate a Doubly Linked List

### ISSUE THREAD

**Issue by deepshikha2708** [aritra-tech/Data-Structure-Algorithm#421]
![image](https://user-images.githubusercontent.com/80972038/187244736-58abb13b-9f6e-4884-bd8d-8309f043827d.png)

**Comment by deepshikha2708** [comment]
can I do this too please @aritra-tech ?

**Comment by aritra-tech** [comment]
> can I do this too please @aritra-tech ?

Yeah, you can
