### ISSUE TITLE
Add Stack and queue Question from Striver SDE sheet

### ISSUE THREAD

**Issue by Rishikavishnoi** [aritra-tech/Data-Structure-Algorithm#427]
[Largest rectangle in a histogram](https://leetcode.com/problems/largest-rectangle-in-histogram/)
[Sliding Window Maximum](https://leetcode.com/problems/sliding-window-maximum/)
[Implement Min Stack](https://leetcode.com/problems/min-stack/)

**Comment by Rishikavishnoi** [comment]
All problems are categorized as hard problems of leetcode.  
I'll Solve in java
@aritra-tech kindly assign it to me

**Comment by aritra-tech** [comment]
Yeah sure
