### ISSUE TITLE
Network Delay Time 

### ISSUE THREAD

**Issue by Anmol-Baranwal** [aritra-tech/Data-Structure-Algorithm#439]
I would like to add the solution to this problem in C++.

According to documentation, it has been asked under Adobe.
- Network Delay Time | Dijkstra, Graph, Bellman Ford

I will make a PR once you assign me this issue.

Do you want me to solve it using both Dijkstra & Bellman Ford?

**Comment by aritra-tech** [comment]
Yeah, sure
