### ISSUE TITLE
N-Queens

### ISSUE THREAD

**Issue by Shweta2024** [aritra-tech/Data-Structure-Algorithm#47]
## Description

The n-queens puzzle is the problem of placing n queens on an n x n chessboard such that no two queens attack each other.

Given an integer n, return all distinct solutions to the n-queens puzzle. You may return the answer in any order.

Each solution contains a distinct board configuration of the n-queens' placement, where 'Q' and '.' both indicate a queen and an empty space, respectively.

**Comment by Shweta2024** [comment]
@aritra-tech  Hello sir, can you please assign me this issue.

**Comment by aritra-tech** [comment]
Yah sure

> @aritra-tech Hello sir, can you please assign me this issue.

Go for it
