### ISSUE TITLE
Add Inorder and Postorder Traversal of Trees | C++

### ISSUE THREAD

**Issue by ashmeet-chhabra** [aritra-tech/Data-Structure-Algorithm#56]
I'll create two separate folders for them [here](https://github.com/aritra-tech/Data-Structure-Algorithm/tree/master/src/Data_Structure/Tree) :)

**Comment by aritra-tech** [comment]
It's created only @ashmeet-chhabra

**Comment by ashmeet-chhabra** [comment]
where? I saw preorder but not inorder and postorder

**Comment by aritra-tech** [comment]
Sure go for it
