### ISSUE TITLE
Convert Sorted Array to Binary Search Tree

### ISSUE THREAD

**Issue by surjyaneeh** [aritra-tech/Data-Structure-Algorithm#58]
problem link: https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/

**Comment by surjyaneeh** [comment]
@aritra-tech may I work on this issue?

**Comment by aritra-tech** [comment]
Ok sure

Make a folder under the tree folder named "Leetcode Problems" and then create another folder named as the problem statement (i.e Sorted_array_to_bst) and then add the java/c++ file over there.
And create a README and add the question link over there.

**Comment by surjyaneeh** [comment]
Okay, I will do the same.

**Comment by surjyaneeh** [comment]
> Ok sure
> 
> Make a folder under the tree folder named "Leetcode Problems" and then create another folder named as the problem statement (i.e Sorted_array_to_bst) and then add the java/c++ file over there. And create a README and add the question link over there.

Is Python also allowed?

**Comment by aritra-tech** [comment]
> > Ok sure
> > Make a folder under the tree folder named "Leetcode Problems" and then create another folder named as the problem statement (i.e Sorted_array_to_bst) and then add the java/c++ file over there. And create a README and add the question link over there.
> 
> Is Python also allowed?

No Python
Just Java/C++/C
