### ISSUE TITLE
Add question of Binary Search in Java.

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#67]
Questions are:
1. [Find Peak Element](https://leetcode.com/problems/find-peak-element/)
2. [Find Minimum in Rotated Sorted Array]( https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/)
3. [Kth Smallest Element in a Sorted Matrix](https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/)
4. [Find the Duplicate Number](https://leetcode.com/problems/find-the-duplicate-number/)

**Comment by JOYPAUL2001** [comment]
I want to work on this issue

**Comment by aritra-tech** [comment]
Ok sure
