### ISSUE TITLE
Lowest common ancestor of Binary Search Tree and Binary Tree

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#68]
Question links are:

1. [Lowest Common Ancestor of a Binary Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/)
2. [Lowest Common Ancestor of a Binary Search Tree](https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/)

**Comment by binayshaw7777** [comment]
,

**Comment by aritra-tech** [comment]
Ok sure
