### ISSUE TITLE
Add Array Insertion in C++

### ISSUE THREAD

**Issue by Rakesh9100** [aritra-tech/Data-Structure-Algorithm#72]

**Comment by Avik-creator** [comment]
Let me have it

**Comment by Avik-creator** [comment]
@aritra-tech

**Comment by Avik-creator** [comment]
@aritra-tech

**Comment by aritra-tech** [comment]
@Avik-creator this issue was created by @Rakesh9100 so this issue will be assigned to @Rakesh9100.
@Avik-creator you can create your new issue or pick any of the issues that is created by me.

**Comment by Rakesh9100** [comment]
> Let me have it

Bro I am not the owner that I have opened a new issue, I am a contributor and I opened the issue by myself.

**Comment by Avik-creator** [comment]
@Rakesh9100 @aritra-tech sorry
