### ISSUE TITLE
Add questions of Recursions in C++

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#74]
Questions are:
1. [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/)
2. [Count Good Numbers](https://leetcode.com/problems/count-good-numbers/)
3. [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/)
4. [Decode String](https://leetcode.com/problems/decode-string/)

**Comment by Rakesh9100** [comment]
> Questions are:
> 
> 1. [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/)
> 2. [Count Good Numbers](https://leetcode.com/problems/count-good-numbers/)
> 3. [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/)
> 4. [Decode String](https://leetcode.com/problems/decode-string/)

Bro Assign me but kindly let me know exactly what kind of question means what work to do in this issue ?

**Comment by aritra-tech** [comment]
> > Questions are:
> > 
> > 1. [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/)
> > 2. [Count Good Numbers](https://leetcode.com/problems/count-good-numbers/)
> > 3. [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/)
> > 4. [Decode String](https://leetcode.com/problems/decode-string/)
> 
> Bro Assign me but kindly let me know exactly what kind of question means what work to do in this issue ?

You have already been assigned with 2 issues, so now I can't assign you more issues. I hope you understand.

**Comment by Rakesh9100** [comment]
> > > Questions are:
> > > 
> > > 1. [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/)
> > > 2. [Count Good Numbers](https://leetcode.com/problems/count-good-numbers/)
> > > 3. [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/)
> > > 4. [Decode String](https://leetcode.com/problems/decode-string/)
> > 
> > 
> > Bro Assign me but kindly let me know exactly what kind of question means what work to do in this issue ?
> 
> You have already been assigned with 2 issues, so now I can't assign you more issues. I hope you understand.

Okay that I will close in 30-45 mins but kindly explain this issue.

**Comment by aritra-tech** [comment]
> > > > Questions are:
> > > > 
> > > > 1. [Add Two Numbers](https://leetcode.com/problems/add-two-numbers/)
> > > > 2. [Count Good Numbers](https://leetcode.com/problems/count-good-numbers/)
> > > > 3. [Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/)
> > > > 4. [Decode String](https://leetcode.com/problems/decode-string/)
> > > 
> > > 
> > > Bro Assign me but kindly let me know exactly what kind of question means what work to do in this issue ?
> > 
> > 
> > You have already been assigned with 2 issues, so now I can't assign you more issues. I hope you understand.
> 
> Okay I understand but I will close those in 30-45 mins but kindly explain this issue.

Ok I will

**Comment by Rakesh9100** [comment]
Kindly tell like I have to add solutions of these 4 questions ?
