### ISSUE TITLE
Swap Nodes in Pairs using Java

### ISSUE THREAD

**Issue by aritra-tech** [aritra-tech/Data-Structure-Algorithm#9]
Write the code for the Swap Nodes in Pairs in Java.

Follow the steps:

go to src -> Algorithm -> create a folder named "Recursion" -> then create another folder for the problem (e.g Swap_Nodes_in_Pairs ) -> there add the java solution and create a README file there add the link of the question.

Make sure to make a folder for every question you solve and the folder should consist of the java file and the README file

Problem Link : [Swap Nodes in Pairs](https://leetcode.com/problems/swap-nodes-in-pairs/)

**Comment by binayshaw7777** [comment]
I would like to work on this issue! @aritra-tech
