### ISSUE TITLE
Minimum cost spanning tree using Prims's algorithm and Kruskal’s algorithm using c++

### ISSUE THREAD

**Issue by vedsom** [aritra-tech/Data-Structure-Algorithm#95]
want to add Minimum cost spanning tree using Prims's algorithm and Kruskal’s algorithm using c++. I am HSOC participant please assign me this issue.

**Comment by vedsom** [comment]
> It's already done @vedsom

can i go with minimum cost spanning tree, shortest path algorithm???

**Comment by aritra-tech** [comment]
Yah, sure
